name: Build wordpress

on: [push]
env:
  BASE_URI: ${{ secrets.BASE_URI }}
  USER_NAME: ${{ secrets.USERNAME }}
  PASSWORD: ${{ secrets.PASSWORD }}
  AUTHORIZATION: Bearer
  status_code:  1
  dict_response: 0
  json_response: 2
  #AUTHORIZATION1: python3 get_token.py

jobs:
  build:
    runs-on: wordpress-test
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install libraries
        run: pip3 install -r requirements.txt

      - name: Install coverage
        run: pip3 install coverage

      - name: Set config variables
        run: |
          touch .env
          echo BASE_URI=$BASE_URI >> .env
          echo USER_NAME=$USER_NAME >> .env
          echo PASSWORD=$PASSWORD >> .env
          echo AUTHORIZATION=$AUTHORIZATION >> .env
          echo status_code=$status_code >> .env
          echo dict_response=$dict_response >> .env 
          echo json_response=$json_response >> .env 
          pwd
          cat .env           

      - name: Run pytest
        run: |          
          python3 -m pytest tests/test_create_page.py         
          python3 -m pytest tests/test_delete_page.py
          python3 -m pytest tests/test_get_page.py

      - name: Coverage
        run: python3 -m coverage run -m pytest

      - name: Generate Report
        run: |
          python3 -m pytest --alluredir=report/allure-report/.
          python3 -m allure serve ./report/allure-report/.

